### ISSUE TITLE
dmenu not working

### ISSUE THREAD

**Issue by drmarwat** [SkywalkerSW5/teaOS#4]
I managed to install teaOS with abinstall 
Mod + D = Dmenu does not work . Edit : Got it working by missing package dmenu

How do I change keybindings according to my choice?

how to launch tea-utils?

**Comment by SkywalkerSW5** [comment]
Hello @drmarwat,

Currently there are a few problems with teaOS, one of them including dmenu not launching, but that has been solved in a later version. I assume you have installed it from the old teaOS 0.2.0 ISO, which had that problem and since has been fixed. The problem was that when the ISO was being made, dmenu wasn't compiled and installed.

To fix that problem, cd into /teaOS/utils/twm/dmenu:

```cd /teaOS/utils/twm/dmenu-5.0```

Then compile and install it:

```make & sudo make install```

That should fix that problem. And to change the keybinds, you have to edit the Dwm config file:

```editor /teaOS/utils/dwm-6.2/config.h```

If this doesn't solve the problem, please let me know!

- skywalkersw5

**Comment by drmarwat** [comment]
Hello ,
I installed dmenu from arch linux repos and it works fine now .

How do I change keybindings according to my choice? I cant locate any sxhkdrc on teaOS

**Comment by SkywalkerSW5** [comment]
Hello,

To add new keybinds to Dwm, you have to edit the config file;

```sudo vim /teaOS/utils/twm/dwm-6.2/config.h```

After that go around to line 96. Create a new line. Example if I were to want to launch Spotify with Shift+S, i would add this line:

```{ ShiftMask, XK_s, spawn, SHCMD("spotify")```

And say I wanted to launch Chrome with Mod+Shift+C:

```{ MODKEY|ShiftMask, XK_C, spawn, SHCMD("google-chrome")```

Adding those around lines 95-6 will add your keybinds. 

However I don't reccomend configuring anything major, until 0.3.2 comes out. Right now there are some major issues and the update changes a lot of things.

-- skywalkersw5

**Comment by SkywalkerSW5** [comment]
Closed due to inactivity
